package com.lacocha.backend.model;

import java.time.Instant;
import java.util.UUID;

import jakarta.persistence.Column;
import jakarta.persistence.Id;
import jakarta.persistence.MappedSuperclass;

/** Fields shared by all events. Events are never edited and the id (UUID) is generated by the phone. */
@MappedSuperclass
public abstract class Event {

    @Id
    private UUID id;
    @Column(name = "dispositivo_id")
    private String deviceId;
    @Column(name = "origen")
    private String source; // sensor | contador | voz | manual
    @Column(name = "registrado_en")
    private Instant recordedAt;
    @Column(name = "recibido_en")
    private Instant receivedAt;

    public UUID getId() { return id; }
    public void setId(UUID id) { this.id = id; }
    public String getDeviceId() { return deviceId; }
    public void setDeviceId(String deviceId) { this.deviceId = deviceId; }
    public String getSource() { return source; }
    public void setSource(String source) { this.source = source; }
    public Instant getRecordedAt() { return recordedAt; }
    public void setRecordedAt(Instant recordedAt) { this.recordedAt = recordedAt; }
    public Instant getReceivedAt() { return receivedAt; }
    public void setReceivedAt(Instant receivedAt) { this.receivedAt = receivedAt; }
}
